### PR TITLE
separate pod name from pod label

### PR DESCRIPTION
**Pull request by joejstuart**

### CODE REVIEW

**Comment by joejstuart** [comment]
This ensures pod label is unique and by default will follow the character set kubernetes requires.

https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set

**Comment by joejstuart** [comment]
I think if you pick "any" it could end up on the master node though right?

**Comment by johnbieren** [comment]
Yeah, I meant if you had multiple nodes with the same label, this change lets you go on "any OF those"

**Comment by joejstuart** [comment]
Gotcha. Yep, that can be done.

**Pull request merged**
